version: '3'
services:
  db:
    restart: always
    build:
      context: ./Database
      dockerfile: Dockerfile
    environment:
      - MYSQL_USER=backend
      - MYSQL_PASSWORD=devonly
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=auto_water
    #volumes:
    #  - /var/backend/mysql_data:/var/lib/mysql:rw,delegated
    #  - /var/backend/mysqld.sock:/var/run/mysqld/mysqld.sock
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    # environment:
    #   - PMA_ABSOLUTE_URI=https://reverse/proxy
    ports:
      - "8080:80"
  server:
    depends_on:
      - db
    restart: always
    build:
      context: ./Server
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    volumes:
      - ./config.py:/backend/config.py
